### ISSUE TITLE
how to use xnview for make qrcode

### ISSUE THREAD

**Issue by taufikmas** [DIYDave/ScrollText-ESP8266#2]
i try to use xnview for convert jpg to .xbm, but resolution not good result in oled.hope your help thanks.

**Comment by DIYDave** [comment]
Hi fixduino,
First you need a jpg or bmp picture with the exact pixel. e.g. 64x64 or 128x64. (Crop / cut / reduce the picture in xnview) Then you must convert it to black&white (1bit) in xnview. (menu "picture"). After that, you save it in xbm-format. I can not say more, because it worked for me. If it does not work, you can send a test picture here.
Good luck and fun.
Dave

**Comment by taufikmas** [comment]
hi dave, thanks for your reply i have try again, yesterday may be my mistake i download the file extension .png not jpg.
all of my step:
1. download file qrcode from qr-code-generator.com
2.step convert pict to B&W mode is via menu image>convert to binary>no Dither in xnview apps. resize to 64x64 res. save the file to bmp.
3.open paint app, invert the color B&W.save file
4.open last filename.bmp via xnview again, and resize canvas to 128x64. save as filename.xbm
done.


thanks alot dave [https://image.prntscr.com/image/G6-4-gC-SbaOsqQWU6mREQ.png](url)
video : [https://youtu.be/QcxakOdCklI](url)
