### ISSUE TITLE
can t get serverscript working

### ISSUE THREAD

**Issue by tolletje223** [DIYDave/ScrollText-ESP8266#3]
Dave, i tried several hosts to get my serverscript working but it will not display the text on the matrix. Online , i can fill in the text i want to send, but it never reaches the matrix . what am i doing wrong, any help please?

**Comment by DIYDave** [comment]
Hi Tolletje
The problem could be missing rights
For me, the server script runs on a NAS.
The script creates a text file with the name: "MeinText.txt" and the content + EOT at the end.
Did it do that?

In order to access this file from ESP, at least read rights for this file must be assigned.
For me there is a group "http" which has read rights for all websites.
Since this text file is not part of the normal website, it must be configured individually.

I hope it helps.
Greetings and good luck
Dave
